### PR TITLE
fix(import settings): allow importing all files on android 9 & below

### LINKED ISSUE #1056: bug: Exported settings cannot be imported back
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube v18.24.37

### Bug description

I couldn't import my settings again after doing a clean install, turns out even exported settings on the latest version cannot be imported again, as they're grayed out.

Also on the older version, there was a bug that when you were to modify the files in any way, like moving them to a computer and back, they would not be recognized by the app. (same issue with grayed out files, but worked for newly exported - non-touched files)

### Steps to reproduce

Step 1. Export settings and close the app
Step 2. Re-open the app and try to import the settings (the file will be grayed out)

-- OTHER BUG --

Step 1. Export settings and close the app
Step 2. Move the exported json file directly (without zip) to another device by any means. (Neaby Share, Bluetooth, USB etc.)
Step 3. Move the file back to the phone and try to import it.

### Relevant log output

```shell
no logs
```

### Screenshots or videos

Screenshot of the import file dialog, showing the bottom 2 settings files grayed out.

### Solution

The code behind it doesn't look like there's anything wrong, so i'm guessing this is a bug with the built-in filepicker, or the file writing process.

To fix it, the mime type of the file could be set to "\*/\*" to allow all files. then the file validation could just be made simple as .endswith(".json") inside the onActivityResult() function.

Other solution is a seperate pop-up menu where we could type the filepath of the .json file we want to import.

### Additional context

_No response_

### Device Environment

Android 9, OneUI 1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

### PR DESCRIPTION
**Pull request by 0xD3N1Z**
closes: https://github.com/inotia00/ReVanced_Extended/issues/1056

### CODE REVIEW

**Comment by inotia00** [comment]
I don't want to remove the extension name filter restriction if possible

This is because I don't want to see bug reports from people asking why the import doesn't work after selecting a backup file other than the json file.

So I'd like to remove the extension filter restriction only on devices below Android 9, if possible.

Does this issue only reproduce on Android 9 or lower devices?

**Comment by Adity1243** [comment]
My device is android 12 and i didn't  face this issue I patched YT for 2 time by rvx manager still no issue after trying 2 time.its working.

**Comment by 0xD3N1Z** [comment]
We have limited info on which versions have this bug, for now Android 9 seems to be the only one affected. We need more people, or emulator test to confirm if it's working on 10 & 11.

**Comment by inotia00** [comment]
Thank you

**Pull request merged**
