### PR TITLE
feat(YouTube/Overlay buttons): Add `Mute Video` button

### PR DESCRIPTION
**Pull request by Francesco146**
https://github.com/inotia00/revanced-patches/pull/63

### CODE REVIEW

**Comment by YT-Advanced** [comment]
@Francesco146 Use [this](https://github.com/inotia00/revanced-integrations/blob/revanced-extended/app/src/main/java/app/revanced/integrations/youtube/swipecontrols/controller/AudioVolumeController.kt) and [this](https://github.com/inotia00/revanced-integrations/blob/revanced-extended/app/src/main/java/app/revanced/integrations/youtube/swipecontrols/controller/VolumeKeysController.kt) instead

**Comment by Francesco146** [comment]
VolumeKeyController isn't executed when not instantiated by Swipe controls. I thought about it too but in the end I didn't know how to implement it, and decided to add a global Volume key listener as it requires few lines of code. What do you think, @inotia00 ?

**Comment by inotia00** [comment]
I think it will be easily solved by changing [SwipeControlsHostActivity](https://github.com/inotia00/revanced-integrations/blob/revanced-extended/app/src/main/java/app/revanced/integrations/youtube/swipecontrols/SwipeControlsHostActivity.kt) to a shared class
(Similar to the `PlayerTypeHook` patch)

If you make this change, you don't have to worry about dependencies on the `Swipe controls` patch

**Comment by Francesco146** [comment]
great, I'll take a look at this soon enough

**Comment by Francesco146** [comment]
after much consideration, I was able to get the dynamic icon to go via volume, within the `SwipeControlsHostActivity` class. however, it resulted in a degradation in code quality, complexity and functionality. The use of `KeyEvent` by `VolumeKeysController` makes it possible to detect physical button presses, however this does not always correspond to an actual volume change (see for example if you press the volume up button, which on stock android shows the volume panel, however not changing the actual volume). Using the `android.media.VOLUME_CHANGED_ACTION` signal receiver, on the other hand, makes sure of this. 

I have come to the conclusion that the optimal code is the one proposed in the first place, not questioning that it might need some refactor.

An alternative brought forward by @inotia00 was to cut corners and make the icon not subject to the actual volume, but simply swap between ON and OFF. It can also be done, but since there is an implementation already done, I see no reason to delete it.

**Comment by inotia00** [comment]
The current change does not require a broadcast receiver and does not depend on the `Swipe controls` patch

**Pull request merged**
